DROP TABLE IF EXISTS PLAYER_DETAILS;

CREATE TABLE PLAYER_DETAILS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  player_name VARCHAR(250) NOT NULL,
  balance VARCHAR(250) DEFAULT NULL,
  transaction_id VARCHAR(250) NOT NULL
);

CREATE TABLE TRANSACTIONS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  player_id VARCHAR(250) NOT NULL,
  wager_amount VARCHAR(250) DEFAULT NULL,
  winning_amount VARCHAR(250) DEFAULT NULL,
  CONSTRAINT transaction_fk FOREIGN KEY (player_id) REFERENCES PLAYER_DETAILS (id)
);

INSERT INTO PLAYER_DETAILS VALUES(1, 'player test',1500,1);
INSERT INTO PLAYER_DETAILS VALUES(2, 'player 2',1500,2);

INSERT INTO TRANSACTIONS VALUES(1,1,1500,null);
INSERT INTO TRANSACTIONS VALUES(2,1,500,null);
INSERT INTO TRANSACTIONS VALUES(3,1,null,1000);